### ISSUE TITLE
CV 'bleed' in Hemispheres

### ISSUE THREAD

**Issue by kaffeetrinken** [djphazer/O_C-Phazerville#17]
I noticed some 'bleed' of CV in Hemispheres.
CV2 from right hemisphere influences erratically CV3 in right hemisphere (see pictures attached, CV2 changes clock division in right hemisphere).

![PXL_20230709_214300566](https://github.com/djphazer/O_C-BenisphereSuite/assets/16975700/05383783-675f-4780-9009-5b909e3ae6c1)
![PXL_20230709_214349504](https://github.com/djphazer/O_C-BenisphereSuite/assets/16975700/fc4fe648-3200-4ade-83f0-55518bcd4347)

**Comment by djphazer** [comment]
Does this happen in other firmwares, too? It might be a hardware issue with your unit...

**Comment by djphazer** [comment]
I was able to reproduce this briefly. I'll look into it further.

**Comment by djphazer** [comment]
I don't have a solution yet, but I think I know what's going on... we're pushing the Teensy to the limit!
It seems like there are cases where one processing cycle will overrun the 60us timer and indeed bleed into the next cycle. CV input reads are staggered, spread across 4 cycles. So I'm seeing CV2 bleed into CV3, and also CV4 bleeds into CV1.

TB-3PO is one of the offending applets that occasionally takes too long; Game of Life will also do it. The only applets currently susceptible to the bleed are ClockDiv, ProbMeloD and ProbDiv - where a spontaneous CV input will change a value, but a 0V input will not. I'll most likely modify these applets to make the CV input a modulation of the current setting, rather than an absolute value, and that will mitigate the problem. To actually eliminate the bleed will require some careful optimizations or restructuring of core execution patterns...

**Comment by djphazer** [comment]
Possible fix on the dev/1.6 branch: https://github.com/djphazer/O_C-BenisphereSuite/commit/d775695edbee1aeed9dca513cfbf0a5bc6963d7f

Switching to DMA-based ADC probably eliminates bleed, needs testing...

**Comment by djphazer** [comment]
Just published v1.6.3 with the DMA patch that should fix this. Feel free to reopen if you can still reproduce.
